
spring:
  application:
    name: users

  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: password
      database: letsplay
      port: 27017
      host: localhost
      auto-index-creation: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8083
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: dev-localhost

