spring:
  application.name: registery

server:
  port: 8761
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    key-alias: dev-localhost

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false