spring:
  application:
    name: gateways
  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/users/**
          - id: products
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/products/**
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/