spring:
  application:
    name: gateways
  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: https://localhost:8083
            predicates:
              - Path=/api/v1/users/**
          - id: products
            uri: https://localhost:8084
            predicates:
              - Path=/api/v1/products/**
server:
  port: 8082
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: dev-localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/